version: 0.2 
 
phases: 
  install: 
    runtime-versions: 
      docker: 20
  pre_build: 
    commands: 
      - echo Logging in to Amazon ECR... 
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email) 
      - IMAGE_TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)" 
      - IMAGE_REPO_NAME="my_app" 
      - AWS_ACCOUNT_ID="637210537803" 
      - echo $AWS_DEFAULT_REGION 
      - echo $IMAGE_REPO_NAME 
      - echo $AWS_ACCOUNT_ID 
  build: 
    commands:    
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG . 
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG       
  post_build: 
    commands: 
      - echo Build completed on `date` 
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG 
      - echo updating imagedefinitions.json 
      - sed -i "s/$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com.*$/$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com\/$IMAGE_REPO_NAME:$IMAGE_TAG\"/" imagedefinations.json 
      - cat imagedefinations.json 
artifacts: 
    files: 
      - index.php 
      - imagedefinations.json 
         

